package Daje::Controller::Users::Signup;
use Mojo::Base 'Mojolicious::Controller', -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Signup - It's new $module
#
# SYNOPSIS
# ========
#
#     use Daje::Controller::Signup;
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Signup is ...
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#

use Mojo::JSON qw{ decode_json };
use Data::Dumper;

our $VERSION = "0.05";

sub signup($self) {

    $self->app->log->debug('Daje::Controller::Client::Signup::signup '  . Dumper($self->req->body));
    my $data->{context} = decode_json $self->req->body;

    try {
        $self->workflow_engine->workflow_pkey(0);
        $self->workflow_engine->workflow_name('users_users');
        $self->workflow_engine->context($data);
        $self->workflow_engine->process('register_new_users_user');
        if($self->workflow_engine->error->has_error() == 0) {
            $self->render(json => {result => 1, data => 'OK'});
        } else {
            $self->app->log->error('Daje::Controller::Users::Signup::signup ' . $self->workflow_engine->error->error());
            $self->render(json =>
                {result => 0, data => $self->workflow_engine->error->error()}
            );
        }
    } catch ($e) {
        $self->app->log->error('Daje::Controller::Users::Signup::signup ' . $e);
        $self->render(json => {result => 0, data => $e});
    };
    $self->app->log->debug('Daje::Controller::Users::Signup::signup ends');
}

sub verify($self) {
    $self->app->log->debug('Daje::Controller::Users::Signup::verify '  . Dumper($self->req->body));
    my $data->{context} = decode_json $self->req->body;

    try {

        $self->workflow_engine->workflow_pkey(0);
        $self->workflow_engine->workflow_name('users_users');
        $self->workflow_engine->context($data);
        say "1";
        $self->workflow_engine->process('verify_new_users_user');
        say "2";
        if($self->workflow_engine->error->has_error() == 0) {
            say "3";
            $self->render(json => {result => 1, data => 'OK'});
        } else {
            say "4";
            $self->app->log->error('Daje::Controller::Users::Signup::verify ' . $self->workflow_engine->error->error());
            $self->render(json =>
                {result => 0, data => $self->workflow_engine->error->error()}
            );
        }
    } catch ($e) {
        $self->app->log->error('Daje::Controller::Client::Signup::verify ' . $e);
        $self->render(json => {result => 0, data => $e});
    };
    $self->app->log->debug('Daje::Controller::Client::Users::verify ends');
}
1;

__END__






#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Controller::Signup - It's new $module



=head1 SYNOPSIS


    use Daje::Controller::Signup;



=head1 DESCRIPTION


Daje::Controller::Signup is ...



=head1 REQUIRES

L<Data::Dumper> 

L<Mojo::JSON> 

L<v5.40> 

L<Mojo::Base> 


=head1 METHODS

=head2 signup($self)

 signup($self)();


=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

