package Daje::Controller::Users::UsersUsers;
use Mojo::Base 'Daje::Controller::Users::Super::UsersUsers', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Users::UsersUsers - Controller class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Users::UsersUsers
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Users::UsersUsers is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-02 02:54:28.
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-02 02:54:28 -->

our $VERSION = '0.01';


sub load_complete_user($self) {
    $self->app->log->debug('Daje::Controller::Super::UsersUsers::load_users__fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
        $self->req->headers->header('X-Token-Check')
    );
    my $pkey = $self->param('users_users_pkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->complete_user->load_complete_user_p($companies_pkey, $users_pkey, $pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::UsersUsers::load_users_users_pkey ' . $err);
        $self->render
    });
}

1;

