package Daje::Controller::Users::UsersVerificationCodesList;
use Mojo::Base 'Daje::Controller::Users::Super::UsersVerificationCodesList', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::UsersVerificationCodesList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Users::UsersVerificationCodesList;
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Users::vUsersVerificationCodesList is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-01 16:28:13.
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-01 16:28:13 -->

our $VERSION = '0.01';

1;

