package Daje::Controller::Users::UsersUsersList;
use Mojo::Base 'Daje::Controller::Users::Super::UsersUsersList', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::UsersUsersList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Users::UsersUsersList;
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Users::vUsersUsersList is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-17 11:42:23.
# It will not be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-17 11:42:23 -->

our $VERSION = '0.01';

1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Controller::UsersUsersList - Model class



=head1 SYNOPSIS


      use Daje::Controller::Users::UsersUsersList;





=head1 DESCRIPTION


Daje::Controller::Users::vUsersUsersList is a standard controller



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

