package Daje::Database::View::Super::VCompaniesUsers;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures;

# Autogenerated class Thu Jun 26 17:06:46 2025
# Any manual changes to this class will be overwritten next time its generated

has 'fields' => "'name', 'companies_fkey', 'users_fkey', 'company_type', 'company_phone', 'is_admin', 'regno', 'vatno', 'homepage', 'userid', 'user_phone', 'company_type_fkey', 'active', 'username', 'support'";
has 'primary_keys' => " ";
has 'foreign_keys' => "foreign_keys"
has 'view_name' => "v_companies_users";



sub load_companies_fkey($self, $companies_fkey ) {

    my $result = $self->load_fkey(
        $self->table_name,
        $self->fields,
        'companies_fkey',
        $companies_fkey
    );
    return $result;
}

sub load_users_fkey($self, $users_fkey ) {

    my $result = $self->load_fkey(
        $self->table_name,
        $self->fields,
        'users_fkey',
        $users_fkey
    );
    return $result;
}

sub load_company_type_fkey($self, $company_type_fkey ) {

    my $result = $self->load_fkey(
        $self->table_name,
        $self->fields,
        'company_type_fkey',
        $company_type_fkey
    );
    return $result;
}



