package Daje::Database::View::Super::vUsersVerificationCodesList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vUsersVerificationCodesList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vUsersVerificationCodesList;
#
#       my $table = Daje::Database::View::Super::vUsersVerificationCodesList->new(db => $db);
#
#       my $result = $table->load_users_verification_codes_pkey($self, $users_verification_codes_pkey);
#
#       my $result = $table->load_users_users_fkey($self, $users_users_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::UsersVerificationCodesList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-04-08 13:48:23.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-04-08 13:48:23 -->

our $VERSION = '0.01';

has 'fields' => '"users_verification_codes_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","verification_code","users_users_fkey"';
has 'primary_key_name' => "users_verification_codes_pkey";
has 'table_name' => "v_users_verification_codes_list";

async sub load_all_users_users_list_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_users_users_list($companies_pkey, $users_pkey);
}

sub load_all_users_users_list($self, $companies_pkey, $users_pkey) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), { companies_companies_fkey => $companies_pkey }
    );
}

async sub load_users_users_list_p($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_users_users_list($companies_pkey, $users_pkey, $key_value);
}

sub load_users_users_list($self, $companies_pkey, $users_pkey, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_users_verification_codes_p($self, $companies_pkey, $users_pkey) {
    return $self->load_all_users_verification_codes($companies_pkey, $users_pkey);
}

sub load_all_users_verification_codes($self, $companies_pkey, $users_pkey) {    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );}
1;


