package Daje::Database::View::Super::vUsersUsers;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vUsersUsers - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vUsersUsers;
#
#       my $table = Daje::Database::View::Super::vUsersUsers->new(db => $db);
#
#       my $result = $table->load_users_users_pkey($self, $users_users_pkey);
##
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::vUsersUsers is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-17 11:42:23.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-01-17 11:42:23 -->

our $VERSION = '0.01';

has 'fields' => '"users_users_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","mail","password","name","active"';
has 'primary_key_name' => "users_users_pkey";
has 'table_name' => "v_users_users";


async sub load_users_users_pkey_p($self, $users_users_pkey) {
    return $self->load_users_users_pkey($users_users_pkey);
}

sub load_users_users_pkey($self, $users_users_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $users_users_pkey
    );
}

1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::View::Super::vUsersUsers - Daje db model



=head1 SYNOPSIS



      use Daje::Database::View::Super::vUsersUsers;

      my $table = Daje::Database::View::Super::vUsersUsers->new(db => $db);

      my $result = $table->load_users_users_pkey($self, $users_users_pkey);





=head1 DESCRIPTION


Daje::Database::View::Super::vUsersUsers is a View super class



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

