package Daje::Database::View::Super::vUsersUsersList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vUsersUsersList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vUsersUsersList;
#
#       my $table = Daje::Database::View::Super::vUsersUsersList->new(db => $db);
#
#       my $result = $table->load_users_users_pkey($self, $users_users_pkey);
#
#       my $result = $table->load_users_workflow_fkey($self, $users_workflow_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::UsersUsersList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-01 16:28:12.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-02-01 16:28:12 -->

our $VERSION = '0.01';

has 'fields' => '"users_users_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
"users_workflow_fkey","avatar","mail","password","name","active"';
has 'primary_key_name' => "users_users_pkey";
has 'table_name' => "v_users_users_list";

async sub load_all_users_workflow_list_p($self) {
    return $self->load_all_users_workflow_list();
}

sub load_all_users_workflow_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_users_workflow_list_p($self, $key_value) {
    return $self->load_users_workflow_list($key_value);
}

sub load_users_workflow_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}
async sub load_all_users_users_p($self) {
    return $self->load_all_users_users();
}

sub load_all_users_users($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}
1;


