package Daje::Database::Model::CompaniesUsers;
use Mojo::Base 'Daje::Database::Model::Super::CompaniesUsers', -base, -signatures;

# Autogenerated class Thu Jun 26 17:06:46 2025
# This class is generated once. Any over rides or special methods should be put here



1;

