package Daje::Database::Model::Login;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -async_await;
use v5.42;

# Autogenerated class Sun Feb  9 13:11:20 2025
# This class is generated once. Any over rides or special methods should be put here

# NAME
# ====
#
#      Daje::Database::Model::Login - It's the login class for users
#
#
# REQUIRES
# ========
#
# use Mojo::Base;
# use Daje::Database::Model::Super::Users;
#
# DESCRIPTION
# ===========
#
# Daje::Database::Model::Login is logging in users
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#
#

use Data::Dumper;
our $VERSION = "0.01";

has 'pg';

sub login ($self, $mail, $password) {

    my $login_stmt = qq{
        SELECT users_users_pkey, mail, name, support, password
            FROM users_users
           WHERE mail = ? AND password = ? AND active = true
    };

    my $result = $self->pg->db->query($login_stmt,($mail, $password));

    my $hash;
    $hash = $result->hash if $result->rows;
    if(!defined $hash) {
        $login_stmt = qq{
        SELECT count(*) as inactive
            FROM users_users
           WHERE mail = ? AND active = false
        };

        $result = $self->pg->db->query($login_stmt,($mail));
        $hash = $result->hash if $result->rows;
        if($hash->{inactive} == 1) {
            $hash = {};
            $hash->{status} = "inactive";
        } elsif ($hash->{inactive} == 0) {
            $login_stmt = qq{
            SELECT count(*) as exists
                FROM users_users
               WHERE mail = ?
            };
            $result = $self->pg->db->query($login_stmt,($mail));
            $hash = $result->hash if $result->rows;
            if($hash->{exists} == 0) {
                $hash = {};
                $hash->{status} = "nonexistent";
            } else {
                $hash = {};
                $hash->{status} = "exists";
            }
        }
    }
    say "Login " . Dumper($hash);
    return $hash;
}
sub user_inactive ( $mail, $password) {

}

sub check_creds ($self, $userid, $password) {

    my $check_stmt = qq{
        SELECT count(*) as exists
            FROM users_users
           WHERE userid = ? AND passwd = ? AND active = true
    };

    my $result = $self->pg->db->query(
        $check_stmt,($userid, $password)
    )->hash->{exists};

    return $result;
}




1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Model::Login


=head1 DESCRIPTION

Autogenerated class Sun Feb  9 13:11:20 2025
This class is generated once. Any over rides or special methods should be put here


=head1 REQUIRES

L<Digest::SHA> 

L<Data::Dumper> 

L<Mojo::Base> 


=head1 METHODS

=head2 check_creds

 check_creds();

=head2 login

 login();


=cut

