package Daje::Database::Model::UsersUsers;
use Mojo::Base 'Daje::Database::Model::Super::UsersUsers', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::Model::UsersUsers - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::Model::UsersUsers;
#
#       my $class = Daje::Database::Model::UsersUsers->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::Model::UsersUsers is the model
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::Model::Super::UsersUsers#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-01-17 11:42:23.
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file 2026-01-17 11:42:23 -->

use DBD::Pg qw(:pg_types);

our $VERSION = '0.01';

1;

sub insert($self, $data) {
    my $avatar = $data->{avatar};
    delete $data->{avatar};

    my $result = $self->SUPER::insert($data);
    $self->avatar($result->{data}->{users_users_pkey},$avatar);

    return $result;
}

sub update($self, $data) {
    my $avatar = $data->{avatar};
    delete $data->{avatar};

    my $result = $self->SUPER::update($data);
    $self->avatar($data->{users_users_pkey},$avatar);

    return $result;
}

sub avatar($self, $users_users_pkey, $avatar) {
    my $stmt = qq{ UPDATE users_users SET avatar = ? WHERE users_users_pkey = $users_users_pkey};

    $self->db->query($stmt, {type => PG_BYTEA, value => $avatar});
}

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::Model::UsersUsers - Model class



=head1 SYNOPSIS


      use Daje::Database::Model::UsersUsers;

      my $class = Daje::Database::Model::UsersUsers->new(db => $db);



=head1 DESCRIPTION


Daje::Database::Model::UsersUsers is the model

class that's only generated once. It inherits all

methods from Daje::Database::Model::Super::UsersUsers#
This class is meant for non standard methods.



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

