package Daje::Database::Model::Workflow;
use Mojo::Base 'Daje::Database::Model::Super::Workflow', -base, -signatures;

# Autogenerated class Thu Jun 26 17:06:45 2025
# This class is generated once. Any over rides or special methods should be put here



1;

