package Daje::Plugin::Users::Helpers;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Users::Helpers - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::Users::Helpers;
#
#       my $class = Daje::Plugin::Users::Helpers->new();
#       $app->helper(
#           v_users_users => sub {
#               state  $v_users_users = Daje::Database::Model::vUsersUsers->new(db => shift->pg->db)
#        });#
#       $app->helper(
#           v_users_users_list => sub {
#               state  $v_users_users_list = Daje::Database::Model::vUsersUsersList->new(db => shift->pg->db)
#        });#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Users::Helpers is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-17 11:42:23.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-17 11:42:23 -->

use Daje::Database::View::vUsersUsers;# Lists
use Daje::Database::View::vUsersUsersList;

our $VERSION = '0.01';

sub helpers($self, $app, $config) {

    $app->helper(
        v_users_users => sub {
            state  $v_users_users = Daje::Database::View::vUsersUsers->new(db => shift->pg->db)
        });    # Lists
    $app->helper(
        v_users_users_list => sub {
            state  $v_users_users_list = Daje::Database::View::vUsersUsersList->new(db => shift->pg->db)
        });}

1;




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Plugin::Users::Helpers - Model class



=head1 SYNOPSIS


      use Daje::Plugin::Users::Helpers;

      my $class = Daje::Plugin::Users::Helpers->new();
      $app->helper(
          v_users_users => sub {
              state  $v_users_users = Daje::Database::Model::vUsersUsers->new(db => shift->pg->db)
       });#
      $app->helper(
          v_users_users_list => sub {
              state  $v_users_users_list = Daje::Database::Model::vUsersUsersList->new(db => shift->pg->db)
       });#


=head1 DESCRIPTION


Daje::Plugin::Users::Helpers is the standard routes



=head1 REQUIRES

L<Daje::Database::View::vUsersUsersList> 

L<Daje::Database::View::vUsersUsers> Lists

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

