package Daje::Plugin::Users::Routes;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Users::Routes - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::Users::Routes;
#
#       my $class = Daje::Plugin::Users::Routes->new();
#       $r->get('/users/api/v1/users/:users_users_pkey');#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Users::Routes is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-17 11:42:23.
# It will be generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-17 11:42:23 -->

our $VERSION = '0.01';

sub routes($self, $app, $config) {
    my $r = $app->routes;
    $r->get('/users/api/v1/users/:users_users_pkey')->to('UsersUsers#users_users_pkey');

    $r->get('/users/api/v1/users_list_all/')->to('UsersUsersList#load_all_users_users');
}

