package Daje::Database::Users;
use Mojo::Base -base;
use v5.42;

our $VERSION = '1';

1;

__DATA__

@@ users

-- 1 up

-- Autogenerated file, any changes to this file will be over written.
-- Last generated 2026-02-16 16:37:16

    
CREATE TABLE IF NOT EXISTS users_verification_codes
(
    users_verification_codes_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                verification_code  VARCHAR  NOT NULL ,
                    users_users_fkey BIGINT UNIQUE NOT NULL,
                CONSTRAINT users_verification_codes_pkey PRIMARY KEY (users_verification_codes_pkey)
);
    
CREATE TABLE IF NOT EXISTS users_users
(
    users_users_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            users_workflow_fkey BIGINT  NOT NULL,
                        avatar  VARCHAR  NOT NULL DEFAULT '' ,
                        mail  VARCHAR  UNIQUE  NOT NULL ,
                        password  VARCHAR  NOT NULL ,
                        name  VARCHAR  NOT NULL DEFAULT '' ,
                        active  BOOLEAN  NOT NULL DEFAULT true ,
                        comment  VARCHAR  NOT NULL DEFAULT '' ,
                        position  VARCHAR  NOT NULL DEFAULT '' ,
                        biography  VARCHAR  NOT NULL DEFAULT '' ,
                    authorities_role_fkey BIGINT  ,
                        phone  VARCHAR  NOT NULL DEFAULT '' ,
                        department  VARCHAR  NOT NULL DEFAULT '' ,
                        employed  BOOLEAN  NOT NULL DEFAULT true ,
                        verified  BOOLEAN  NOT NULL DEFAULT false ,
                CONSTRAINT users_users_pkey PRIMARY KEY (users_users_pkey)
);
    
CREATE TABLE IF NOT EXISTS users_documentation
(
    users_documentation_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                document_name  VARCHAR  NOT NULL ,
                    users_users_fkey BIGINT  NOT NULL,
                        "type"  VARCHAR  NOT NULL ,
                CONSTRAINT users_documentation_pkey PRIMARY KEY (users_documentation_pkey)
);
    

CREATE OR REPLACE VIEW v_users_verification_codes AS
    SELECT users_verification_codes_pkey, editnum, insby, insdatetime, modby, moddatetime, verification_code,
     users_users_fkey
          FROM users_verification_codes;
CREATE OR REPLACE VIEW v_users_users AS
    SELECT users_users_pkey, editnum, insby, insdatetime, modby, moddatetime,users_workflow_fkey,
      avatar,
      mail,
      password,
      name,
      active,
      comment,
      position,
      biography,
     authorities_role_fkey,
      phone,
      department,
      employed,
      verified
          FROM users_users;
CREATE OR REPLACE VIEW v_users_documentation AS
    SELECT users_documentation_pkey, editnum, insby, insdatetime, modby, moddatetime, document_name,
     users_users_fkey,
      "type"
          FROM users_documentation;


CREATE OR REPLACE VIEW v_users_verification_codes_list AS
    SELECT users_verification_codes_pkey, editnum, insby, insdatetime, modby, moddatetime, verification_code,users_users_fkey     FROM users_verification_codes;

CREATE OR REPLACE VIEW v_users_users_list AS
    SELECT users_users_pkey, editnum, insby, insdatetime, modby, moddatetime,users_workflow_fkey, avatar, mail, password, name, active, comment, position, biography,      (SELECT name FROM authorities_role WHERE authorities_role_pkey = authorities_role_fkey) as authorities_role_name,authorities_role_fkey, phone, department, employed, verified     FROM users_users;

CREATE OR REPLACE VIEW v_users_documentation_list AS
    SELECT users_documentation_pkey, editnum, insby, insdatetime, modby, moddatetime, document_name,users_users_fkey, "type"     FROM users_documentation;





  ALTER TABLE users_verification_codes
    ADD CONSTRAINT users_verification_codes_users_users_fkey
        FOREIGN KEY (users_users_fkey)    REFERENCES users_users (users_users_pkey);

CREATE INDEX ind_users_verification_codes_users_fkey
    ON users_verification_codes(users_users_fkey);

    ALTER TABLE users_users
    ADD CONSTRAINT users_users_users_workflow_fkey
        FOREIGN KEY (users_workflow_fkey)
    REFERENCES workflow (workflow_pkey);
CREATE INDEX ind_users_users_workflow_fkey
    ON users_users(users_workflow_fkey);

  
  
  
  
  
  
  
  
  ALTER TABLE users_users
    ADD CONSTRAINT authorities_users_authorities_role_fkey
        FOREIGN KEY (authorities_role_fkey)    REFERENCES authorities_role (authorities_role_pkey);


CREATE INDEX ind_authorities_users_role_fkey
    ON users_users(authorities_role_fkey);

  
  
  
  
  
    
  ALTER TABLE users_documentation
    ADD CONSTRAINT users_documentation_users_users_fkey
        FOREIGN KEY (users_users_fkey)    REFERENCES users_users (users_users_pkey);

CREATE INDEX ind_users_documentation_users_fkey
    ON users_documentation(users_users_fkey);

  
    


-- 1 down



@@ the_end


