package Daje::Database::Users;
use Mojo::Base -base;
use v5.42;

our $VERSION = '1';

1;

__DATA__

@@ users

-- 1 up

-- Autogenerated file, any changes to this file will be over written.
-- Last generated 2026-01-17 11:42:23

    
CREATE TABLE IF NOT EXISTS users_users
(
    users_users_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                mail  VARCHAR  UNIQUE  NOT NULL ,
                        password  VARCHAR  NOT NULL ,
                        name  VARCHAR  NOT NULL DEFAULT '' ,
                        active  BOOLEAN  NOT NULL DEFAULT true ,
                        support  BOOLEAN  NOT NULL DEFAULT false ,
                CONSTRAINT users_users_pkey PRIMARY KEY (users_users_pkey)
);
    

CREATE OR REPLACE VIEW v_users_users AS
    SELECT users_users_pkey, editnum, insby, insdatetime, modby, moddatetime, mail,
      password,
      name,
      active,
      support
          FROM users_users;


CREATE OR REPLACE VIEW v_users_users_list AS
    SELECT users_users_pkey, editnum, insby, insdatetime, modby, moddatetime, mail, password, name, active, support     FROM users_users;




            
-- 1 down



@@ the_end

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Templates::Tools::Generate::SQL; - It creates perl code



=head1 SYNOPSIS


    use Daje::Templates::Tools::Generate::SQL;

    Provides a method for the template to be loaded into the data structure

    sub length_default_calc($self) returns a sub for setting details in template.




=head1 DESCRIPTION


Daje::Templates::Tools::Generate::SQL; is a module that retrieves data from a View



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS

=head2 length_default_calc($self)

 length_default_calc($self)();

=head2 set_subs($self)

 set_subs($self)();

NAME
====

Daje::Templates::Tools::Generate::SQL; - It creates perl code

SYNOPSIS
========

    use Daje::Templates::Tools::Generate::SQL;

    Provides a method for the template to be loaded into the data structure

    sub length_default_calc($self) returns a sub for setting details in template.


DESCRIPTION
===========

Daje::Templates::Tools::Generate::SQL; is a module that retrieves data from a View

LICENSE
=======

Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

AUTHOR
======

janeskil1525 E<lt>janeskil1525@gmail.comE<gt>




=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

