package Daje::Database::Users;
use Mojo::Base -base;
use v5.42;

our $VERSION = '1';

1;

__DATA__

@@ users

-- 1 up

-- Autogenerated file, any changes to this file will be over written.
-- Last generated 2026-02-02 02:54:27

    
CREATE TABLE IF NOT EXISTS users_users
(
    users_users_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            users_workflow_fkey BIGINT  NOT NULL,
                        avatar  VARCHAR  NOT NULL DEFAULT '' ,
                        mail  VARCHAR  UNIQUE  NOT NULL ,
                        password  VARCHAR  NOT NULL ,
                        name  VARCHAR  NOT NULL DEFAULT '' ,
                        active  BOOLEAN  NOT NULL DEFAULT true ,
                CONSTRAINT users_users_pkey PRIMARY KEY (users_users_pkey)
);
    
CREATE TABLE IF NOT EXISTS users_verification_codes
(
    users_verification_codes_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                verification_code  VARCHAR  NOT NULL ,
                    users_users_fkey BIGINT UNIQUE NOT NULL,
                CONSTRAINT users_verification_codes_pkey PRIMARY KEY (users_verification_codes_pkey)
);
    

CREATE OR REPLACE VIEW v_users_users AS
    SELECT users_users_pkey, editnum, insby, insdatetime, modby, moddatetime,users_workflow_fkey,
      avatar,
      mail,
      password,
      name,
      active
          FROM users_users;
CREATE OR REPLACE VIEW v_users_verification_codes AS
    SELECT users_verification_codes_pkey, editnum, insby, insdatetime, modby, moddatetime, verification_code,
     users_users_fkey
          FROM users_verification_codes;


CREATE OR REPLACE VIEW v_users_users_list AS
    SELECT users_users_pkey, editnum, insby, insdatetime, modby, moddatetime,users_workflow_fkey, avatar, mail, password, name, active     FROM users_users;

CREATE OR REPLACE VIEW v_users_verification_codes_list AS
    SELECT users_verification_codes_pkey, editnum, insby, insdatetime, modby, moddatetime, verification_code,users_users_fkey     FROM users_verification_codes;




ALTER TABLE users_users
    ADD CONSTRAINT users_users_users_workflow_fkey
FOREIGN KEY (users_workflow_fkey)
    REFERENCES workflow (workflow_pkey);

CREATE INDEX ind_users_users_workflow_fkey
    ON users_users(users_workflow_fkey);

  
  
  
  
  
    
  ALTER TABLE users_verification_codes
    ADD CONSTRAINT users_verification_codes_users_users_fkey
FOREIGN KEY (users_users_fkey)
    REFERENCES users_users (users_users_pkey);


CREATE INDEX ind_users_verification_codes_users_fkey
    ON users_verification_codes(users_users_fkey);

    
-- 1 down



@@ the_end


