package Daje::Database::View::vUsersUsers;
use Mojo::Base 'Daje::Database::View::Super::vUsersUsers', -base, -async_await, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::vUsersUsers - View class
#
# SYNOPSIS
# ========
#
#       use Daje::Database::View::vUsersUsers;
#
#       my $class = Daje::Database::View::vUsersUsers->new(db => $db);
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::vUsersUsers is the View
#
# class that's only generated once. It inherits all
#
# methods from Daje::Database::View::Super::vUsersUsers#
# This class is meant for non standard methods.
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-01-17 11:42:23.
# It will not be touched by Daje Tools again.
# <!-- Autogenerated file 2026-01-17 11:42:23 -->


our $VERSION = '0.01';

1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::View::vUsersUsers - View class



=head1 SYNOPSIS


      use Daje::Database::View::vUsersUsers;

      my $class = Daje::Database::View::vUsersUsers->new(db => $db);



=head1 DESCRIPTION


Daje::Database::View::vUsersUsers is the View

class that's only generated once. It inherits all

methods from Daje::Database::View::Super::vUsersUsers#
This class is meant for non standard methods.



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

