package Daje::Workflow::Activities::Users::Activity;
use Mojo::Base 'Daje::Workflow::Common::Activity::Base', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Workflow::Activities::Users::Activity - A workflow activity
#
# SYNOPSIS
# ========
#;
#
# DESCRIPTION
# ===========
#
# Daje::Workflow::Activities::Users::Activity is a Daje workflow activity.
#
# METHODS
# =======
#
# Daje::Workflow::Activities::Users::Activity inherits all methods from
# Daje::Workflow::Activities::Tools::Generate::Base and implements the following new ones.
#
# activity
#
# SEE ALSO
# ========
#
# Mojolicious, Mojolicious::Guides, https://mojolicious.org.
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-02-13 15:05:02.
# It will not be touched by Daje Tools again.

# <!-- Autogenerated file 2026-02-13 15:05:02 -->

use Daje::Database::Model::CompaniesUsers;
use POSIX;
use Digest::SHA qw{sha512_base64};
use Data::Dumper;

sub save($self) {

    $self->model->insert_history(
        "New client",
        "Daje::Workflow::Activities::Users::Activity::save",
        1
    );

    my $data = $self->context->{context}->{payload};
    $data->{password} = sha512_base64($data->{password});
    try {

        my $dbclass = Daje::Database::Model::UsersUsers->new(db => $self->db);
        my $hist = $data;
        #delete $hist->{password};
        $self->model->insert_history(
            "New / Updated user " . $dbclass->table_name() . Dumper($hist), " insert / update", 2
        );

        $data->{$dbclass->workflow()} = $self->context->{context}->{workflow}->{workflow_fkey}
            if($dbclass->workflow());

        my $authorities_role_fkey = $data->{authorities_role_fkey};
        my $position = $data->{position};
        delete $data->{ "authorities_role_fkey" };
        delete $data->{"position"};

        say "Data " . Dumper($data);
        if( !exists $data->{users_users_pkey} || $data->{users_users_pkey} == 0) {

            delete $data->{'users_users_pkey'};
            $self->context->{context}->{payload}->{$dbclass->primary_key_name()} = $dbclass->insert(
                $data
            )->{data}->{$dbclass->primary_key_name()};

            Daje::Database::Model::CompaniesUsers->new(
                db => $self->db
            )->insert({
                companies_companies_fkey => $self->context->{context}->{companies_fkey},
                users_users_fkey         => $self->context->{context}->{payload}->{users_users_pkey},
                authorities_role_fkey    => $authorities_role_fkey,
                position                 => $position,
                comment                  => "Created " . strftime "%Y-%m-%d %H:%M:%S", localtime time,
            });
        } else {
            $dbclass->update($data, {
                users_users_pkey => $data->{users_users_pkey}
            });

            Daje::Database::Model::CompaniesUsers->new(
                db => $self->db
            )->update({
                authorities_role_fkey    => $authorities_role_fkey,
                position                 => $position,
                comment                  => "Updated " . strftime "%Y-%m-%d %H:%M:%S", localtime time,
            },{
                companies_companies_fkey => $self->context->{context}->{companies_fkey},
                users_users_fkey         => $data->{users_users_pkey},
            });
        }


    } catch ($e) {
        $self->error->add_error($e);
    };

}

1;

